### PR TITLE
Use a max scale of 2 on RZBorders

### PR DESCRIPTION
**Pull request by dostrander**
. This allows for the borders to layout properly on 6 and 6+

Note the underlying implementation of the borders should be changed, however this is a good quick fix. A better way to go about adding borders would be to start using 1 px "hairline" views instead of trying to draw the borders manually.

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
@dostrander why not just set the view's layer's border?

**Comment by arrouse** [comment]
@dostrander this seems to have a lot of extra commit's in it.  You may want to make your changes off of develop and then just get them in.  Or we can go and clear up some of these PR's.

**Comment by dostrander** [comment]
@arrouse I had to pull in @nbonatsakis PR as well because we need that as well. Should we just do those PRs separately?

**Comment by arrouse** [comment]
@dostrander Generally Yea.  You would get this pulled into Develop and then you could pull develop into your other PR.  Since the other PR isn't mergeable(might not be a word) I think that would be your best option.

**Pull request closed without merging**
