### PR TITLE
need double underscore for typeof macros

### PR DESCRIPTION
**Pull request by sixstringtheory**
Trying to build with `typeof(self)` generated build errors in my project.

Changing them to `__typeof(self)` resolved the errors.

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
What were the errors? Which compiler flag threw them? I thought `__typeof` was for compatibility with legacy compilers.

**Comment by mr-fixit** [comment]
Zev, the underscored version is required for strict ISO C compliance, because 'typeof' is a language extension.

see:
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html
http://stackoverflow.com/questions/14877415/difference-between-typeof-typeof-and-typeof-objective-c

**Comment by ZevEisenberg** [comment]
We've been using `typeof` in recent projects with no issues. We could change it if it will increase compatibility with projects that use RZUtils, but I'm still curious what part of @sixstringtheory's project is grumpy about `typeof`.

**Comment by sixstringtheory** [comment]
Issue is resolved when setting "C language dialect" to "compiler default" (which currently sets it to GNU99)

**Comment by arrouse** [comment]
@sixstringtheory can we close this PR?

**Comment by ZevEisenberg** [comment]
@arrouse it would be reasonable to change the style guide to say that we should use `__typeof`, either always or at least for public code.

**Comment by ZevEisenberg** [comment]
@arrouse and to merge this fix.

**Comment by mr-fixit** [comment]
The goal of avoiding the double-underscore is foiled in this case by the need for '__' in another compiler extension on the same line ('__weak').

**Pull request merged**
